PXE-1304: Update component-status custom bloc classnames
rapid7/exporter-documentation pull request #2
Opened 2022-10-24 13:50 UTC by smcmullan-r7

## Description (brief description on what changes have been added)

Updated component-status bloc and SCSS classnames from component-health-row to component-status.
Updated exporter json default information.

JIRA: https://issues.corp.rapid7.com/browse/PXE-1039

## Screenshots (if appropriate):
Tested via test design system and test-documentation-exporter. Please note image is zoomed in

**Before changes**
![Screenshot 2022-10-24 at 14 44 45](https://user-images.githubusercontent.com/107042274/197540633-2e0fb424-3f31-4262-9bb3-54f75774a011.png)
**After changes**
![Screenshot 2022-10-24 at 14 44 45](https://user-images.githubusercontent.com/107042274/197540633-2e0fb424-3f31-4262-9bb3-54f75774a011.png)

## Determine your change type:

_When determining the type of change, only the acceptable use of the component or style should be used to classify the effects of the change._

- Is this a MAJOR? _(If you can check any of these, you should mark your PR as a Major)_
  - [ ] How the component is used/consumed has changed? _(API change, etc)_
  - [ ] The component/module name in the [theme mixin](https://github.com/rapid7/rapid7-ui/blob/master/src/scss/base/_utilities.scss#L136) has changed?
  - ~~The name of the styles mixin has changed?~~
  - [ ] The classnames associated with a component have changed?
  - If you've checked any boxes above: [Read This](https://github.com/rapid7/rapid7-ui/blob/master/CONTRIBUTING.md#release-and-deployment).
- Is this a MINOR? _(you haven't checked anything above, of course)_
  - [X] You're adding completely new functionality
  - [X] The functionality you're adding is **fully** backwards compatible. _(If it isn't, your change is a MAJOR)_
- Is this a PATCH? _(nothing checked above)_
  - [ ] You're fixing existing functionality
  - [ ] The name of the styles mixin has changed?
  - [ ] Your fix is non-breaking
- No release needed
  - [ ] Changes to tests
  - [ ] Changes to Storybook
  - [ ] Changes to documentation / Readme

## Checklist:

- [x] I have ensured backwards compatibility and have discussed a deprecation plan with the UI Platform Working Group (if your changes would be considered a MAJOR).
- [X] I have clearly communicated any SCSS changes that fundamentally change display and layout as per [this proposal](https://docs.google.com/document/d/1dNYFL_7u2J3wImFGZBkaoEfuavtmX_g7LftmNdyV5qo/edit?usp=sharing).
- [] I have updated the documentation accordingly (if changes are required).
- [ ] I have added tests to cover my changes. (if required).
- [ ] I have added a new dependency and properly considered whether that dependency should be in `devDependencies` vs `dependencies`. _for further reading: https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file_
- [X] All new and existing tests passed.
- [X] Added/update story book stories.

2022-10-24 13:53 UTC, msmichova-r7 approved these changes

2022-10-24 14:19 UTC, jpyper-r7 requested changes
Sean all the mixins at the top that builder the super mixin at the bottom, we can prob get rid of those but keep the super mixin 👍🏻 

That is the right way forward now, no more building a billion mixins, we just keep the main one and right the css within it.

Give me a shout if you need some clarification 👍🏻 

Also `!important` tags hmmmmmm?

2022-10-24 14:43 UTC, smcmullan-r7 commented
> Sean all the mixins at the top that builder the super mixin at the bottom, we can prob get rid of those but keep the super mixin 👍🏻
> 
> That is the right way forward now, no more building a billion mixins, we just keep the main one and right the css within it.
> 
> Give me a shout if you need some clarification 👍🏻
> 
> Also `!important` tags hmmmmmm?

Ill update the scss to match the new format, ill also remove the important tag lol!

2022-10-25 09:20 UTC, jpyper-r7 approved these changes

2022-10-25 09:21 UTC, merged